### ISSUE TITLE
How would this work with API calls?

### ISSUE THREAD

**Issue by jaichandra** [JannicBeck/ngrx-undoable#1]
If I have API calls within my actions, how would undo work, because undo would need a different API call to undo what was updated on server.

**Comment by JannicBeck** [comment]
Could you elaborate further on what method/library you use to make API calls within your actions? Do you mean [thunks](https://github.com/gaearon/redux-thunk)?

**Comment by GuillaumeUnice** [comment]
Hello there,
Well, I wondered pretty much the same thing. This library works when it comes to undo an action without side effect at all, not only in your reducer (of course) but also with the NGRX Effects.

For instance, I remove a Todo Task then I decide to undo. Basically, the store could recover is initial state but not the server.

That's why I ask if there a way to implement a reverse Effects? Even though you couldn't refind your initial Task because the POST is no idempotent. In this example the idea will be different but we could imagine an approach like that.

But basically undo/redo with non deterministic system doesn't a perfect idea.

I hope the question is more clear now?
What your opinion  @JannicBeck ?

Thanks for all

**Comment by JannicBeck** [comment]
Hey @GuillaumeUnice ,

I'll try to get an example app for your case going over the weekend.

**Comment by GuillaumeUnice** [comment]
Hello @JannicBeck ,
Ok no problem take your time but that's could be very useful not only for me :D

Have a good one,
see you

**Comment by GuillaumeUnice** [comment]
Hi @JannicBeck ,

Thanks a lot for your answer sorry for the delay.
Well, both ideas seem enough to cover all use case I've encounter so thank you so much.

I think the issue could be closed now

See you
