### ISSUE TITLE
What's the difference from undox?

### ISSUE THREAD

**Issue by dantman** [JannicBeck/ngrx-undoable#2]
This library and [undox](https://github.com/JannicBeck/undox) are not completely clear what the difference between the two libraries is.

**Comment by JannicBeck** [comment]
From the motivation section:

- Use undox if your state is fat and your actions are thin and you want maximum performance for that.

- Use this library if you want something in between with a nicer API than undox. (only present state is stored)

Ngrx-undoable stores actions AND the current state

```
{
  past    : [ { type: 'INIT' }, { type: 'INCREMENT' }, { type: 'INCREMENT' } ]
  present : 2
  future  : [ ]
}
```

Undox just stores actions (current state is computed)

```
{
  history : [ { type: 'undox/INIT' }, { type: 'INCREMENT' }, { type: 'INCREMENT' } ],
  index   : 2
}
```

The important thing to know here is: while in undox index is always just a _number_ regardless of how your state looks, in ngrx-undoable the value of present represents your state, which happens to be also a number since we are using the counter example. Hope this helps.

**Comment by dantman** [comment]
Ok, I think I get it after using it. But it would've been nice to have a bullet list when I was trying to evaluate the difference between the two. Or actually a table.

* undox just stores the actions; ngrx-undoable stores the actions and the current state of the store in `present`.
* undox stores actions in a `history` array and the current position as an `index` and increments/decrements it when doing an undo/redo; ngrx-undoable stores previous actions in a `past` array and actions that have been undone in a `future` array, and moves actions from one array to the other when doing an undo/redo.
* undox returns the reducer from its constructor and has `createSelectors` to create selectors from the original reducer; ngrx-undoable returns the reducer and selectors as an object from its constructor.
* Other than this and bikeshed level surface API details, undox and ngrx-undoable function the same. ... (And I'd hope have the same maintenance status and support level)

As a side note, I didn't quite realize the concept of how both libraries work (doing undo by replaying actions without needing to store states or implement 'undo' reducers) until I skimmed the code a little and thought about how they might work.

**Comment by JannicBeck** [comment]
I gave this a thought over the weekend and you're kind of right.

I think at some point the libraries will converge eventually, but I'm not ready yet since they're both pretty young and I don't know all the use cases.

For now I will probably add features to this library first, see open [issues](https://github.com/JannicBeck/ngrx-undoable/issues) and memoization etc. and keep undox more lean and simple and add features later when they proved to be solid.
